- hosts: "{{ groups['es-1'][0] }}"
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  vars:
    - es_nfs_backup_path: "{{ nfs_db_backup_path }}"
    - es_snapshot_host: "{{app_es_snapshot_host}}"
    - snapshot_base_path: "{{app_snapshot_base_path}}"
  roles:
    - role: elasticsearch_backup
      tags: elasticsearch_backup
